=== yanna-stepanova/Java-base/src/main/resources/order.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="order">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="userId" type="xs:long"/>
                <xs:element name="product" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="productId" type="xs:long"/>
                            <xs:element name="productName" type="xs:string"/>
                            <xs:element name="price" type="xs:string"/>
                            <xs:element name="quantity" type="xs:integer"/>
                            <xs:element name="category" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="creationDate" type="xs:string"/>
            </xs:sequence>
            <xs:attribute name="id"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== yanna-stepanova/Java-base/src/main/resources/order.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE order
        [
                <!ELEMENT order (userId,product,creationDate)>
                <!ELEMENT userId (#PCDATA)>
                <!ELEMENT product (productId, productName, price, quantity, category)>
                <!ELEMENT productId (#PCDATA)>
                <!ELEMENT productName (#PCDATA)>
                <!ELEMENT price (#PCDATA)>
                <!ELEMENT quantity (#PCDATA)>
                <!ELEMENT category (#PCDATA)>
                <!ELEMENT creationDate (#PCDATA)>

                <!ATTLIST order id CDATA #REQUIRED>
        ] >

<order id="1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="order.xsd">

    <userId>1</userId>
    <product>
        <productId>1</productId>
        <productName>iPad</productName>
        <price>199.00</price>
        <quantity>5</quantity>
        <category>Music</category>
    </product>
    <creationDate>20-05-08</creationDate>
</order>
